### ISSUE TITLE
Does Not Work on my machine

### ISSUE THREAD

**Issue by VerticalVodka** [Abrynos/Implement.Net#2]
### Description
Wanted to start, but it doesn't

### Expected behaviour
It works

### Current behaviour
It does not

### Possible solution
It works

### Steps to reproduce
Do magic

### Additional information
No

**Comment by Abrynos** [comment]
Hey there!

Thank you for contacting our development team at GitHub.

We believe that your issue does not meet our [contributing guidelines](https://github.com/Abrynos/Implement.Net/blob/master/.github/CONTRIBUTING.md).

**Technical difficulties using the library are not related to development.**

Please check out the [discussions section](https://github.com/Abrynos/Implement.Net/discussions) if you need further help.

Have a nice day!
~Abrynos
